server:
  port: 8082
  servlet:
    context-path: '/ead-course/'

spring:
  application:
    name: ead-course-service
  datasource:
    url: jdbc:postgresql://localhost:5434/ead-course-v2
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non-contextual-creation: true
  rabbitmq:
    addresses: amqps://exoocvsi:Cse2TeWuiUcLuiohi6lGxRuokK82CLwJ@gerbil.rmq.cloudamqp.com/exoocvsi

ead:
  api:
    url:
      user: 'http://ead-authuser-service/ead-authuser'
  broker:
    exchange:
      userEventExchange: ead.userevent
    queue:
      userEventQueue:
        name: ead.userevent.ms.course

logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO

eureka:
  client:
    service-url:
      default-zone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost